services:
  web-app:
    build: null
    env_file: web-app.env
    logging:
      options:
        awslogs-stream: web-app

  web-app-migrator:
    env_file: web-app-migrator.env
    logging:
      options:
        awslogs-stream: web-app-migrator

  sync-service:
    build: null
    env_file: sync-service.env
    logging:
      options:
        awslogs-stream: sync-service

  sync-service-migrator:
    env_file: sync-service-migrator.env
    logging:
      options:
        awslogs-stream: sync-service-migrator

  db:
    env_file: db.env
    logging:
      options:
        awslogs-stream: postgres
    volumes:
      - /mnt/postgres_data:/var/lib/postgresql/data

  caddy:
    env_file: caddy.env
    build: null
    logging:
      options:
        awslogs-stream: caddy
    volumes:
      - /var/log/caddy:/var/log/caddy
