version: '3.8'
services:
  db:
    image: postgres:16
    container_name: sophistree-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sophistree
    ports:
      - "5432:5432"
    volumes:
      - sophistree_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sophistree_data:
    name: sophistree_data
