services:
  web-app:
    build:
      context: ..
      dockerfile: docker/web-app.dockerfile
    image: sophistree/web-app:${VERSION:-latest}
    container_name: sophistree-web-app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://sophistree:${DB_PASSWORD}@db:5432/sophistree
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16
    container_name: sophistree-db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: sophistree
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: sophistree
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sophistree"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  caddy:
    build:
      dockerfile: caddy.dockerfile
    image: sophistree/caddy:${VERSION:-latest}
    container_name: sophistree-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
    name: sophistree_postgres_data
  caddy_data:
  caddy_config:
