name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run type-check-all
      - name: Lint
        run: npm run lint-all
      - name: Format check
        run: npm run format-check-all
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: tapestry-highlights-playwright-report
          path: packages/tapestry-highlights/playwright-report/
          retention-days: 30
      - name: Test
        run: npm run test-all
      - name: Build Dev
        run: npm run build-dev --workspace extension
      - name: Build Prod
        run: npm run build-prod --workspace extension
